package Alojamento;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.kingaspx.util.BrowserUtil;
import com.kingaspx.version.Version;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.Callback;
import com.teamdev.jxbrowser.chromium.JSObject;
import static com.teamdev.jxbrowser.chromium.MediaType.File;
import com.teamdev.jxbrowser.chromium.dom.By;
import com.teamdev.jxbrowser.chromium.dom.DOMDocument;
import com.teamdev.jxbrowser.chromium.dom.DOMElement;
import com.teamdev.jxbrowser.chromium.events.ConsoleEvent;
import com.teamdev.jxbrowser.chromium.events.FinishLoadingEvent;
import com.teamdev.jxbrowser.chromium.events.LoadAdapter;
import com.teamdev.jxbrowser.chromium.events.ScriptContextAdapter;
import com.teamdev.jxbrowser.chromium.events.ScriptContextEvent;
import com.teamdev.jxbrowser.chromium.events.TitleEvent;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;

import java.awt.BorderLayout;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import projeto2trilho.BLL.AlojamentoJpaController;
import projeto2trilho.DAL.Alojamento;

public class CriarAlojamento extends javax.swing.JFrame {

    String cliente;
     int modoOper = 0; // 0 = CRIAR ; 1 = UPDATE
    Alojamento AloToUpdate = null;
    public CriarAlojamento() {
        initComponents();
        open_site();
 
    }
    public CriarAlojamento(String clim) 
    {  
        initComponents();
        this.cliente=clim;       
    }

     public CriarAlojamento(Alojamento alo) {

        // ALTERAR CLIENTE 
        initComponents();
        open_site();
        //this.jLabel6.setText("Alterar Cliente com ID " + uti.getUtilizadorId());
        this.modoOper = 1;

        AloToUpdate = alo;
        
        this.Nome.setText(alo.getAlojamentoNome());
        this.Lat.setText(alo.getAlojamentoLatitude());
        this.Long.setText(alo.getAlojamentoLongitude());
        this.Cp.setText(alo.getAlojamentoCp());
        this.morada.setText(alo.getAlojamentoCidade());
        this.pais.setText(alo.getAlojamentoPais());
        this.Descricao.setText(alo.getAlojamentoDescricao());
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Nome = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        Lat = new javax.swing.JTextField();
        Long = new javax.swing.JTextField();
        Cp = new javax.swing.JTextField();
        morada = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descricao = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jButton1.setText("fotos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        jPanel2.add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 270, 40));

        add.setText("Submeter");
        add.setActionCommand("Adicionar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 100, 50));
        jPanel2.add(Lat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 270, 40));
        jPanel2.add(Long, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 270, 40));

        Cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpActionPerformed(evt);
            }
        });
        jPanel2.add(Cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 270, 40));
        jPanel2.add(morada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 270, 40));
        jPanel2.add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 270, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Adicionar Alojamento");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 240, 40));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 310, 4));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Latitude :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 560, 590));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 100, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Longitude:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Código-Postal:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Descrição:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Nome Do Alojamento:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Morada:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("País:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_final.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home_final.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, -1, -1));

        Descricao.setColumns(20);
        Descricao.setRows(5);
        jScrollPane1.setViewportView(Descricao);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 320, 150));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ess.PNG"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alog.PNG"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 520, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (modoOper == 0) {
            if (!Nome.getText().isEmpty() && !Lat.getText().isEmpty() && !Long.getText().isEmpty() && !Cp.getText().isEmpty() && !Descricao.getText().isEmpty() && !pais.getText().isEmpty() ){     
            Alojamento alo = new Alojamento();

            alo.setAlojamentoNome(Nome.getText());
            //String temp = cidade.getSelectedItem().toString();
          //  alo.setAlojamentoCidade(temp);
            alo.setAlojamentoLatitude(Lat.getText());
            alo.setAlojamentoLongitude(Long.getText());
            alo.setAlojamentoCp(Cp.getText());
            alo.setAlojamentoCidade(morada.getText());
            alo.setAlojamentoPais(pais.getText());
            alo.setAlojamentoDescricao(Descricao.getText());
            

            AlojamentoJpaController.create(alo);

            JOptionPane.showMessageDialog(null, "Alojamento criado Com sucesso!");
            ListarAlojamento listarAlojamento = new ListarAlojamento();
            listarAlojamento.setVisible(true);            
            this.setVisible(false);
            }
            else{
                this.jLabel13.setText("Campos Vazios");
            }
             }
        else {
            if(!Nome.getText().isEmpty() && !Lat.getText().isEmpty() && !Long.getText().isEmpty() && !Cp.getText().isEmpty() && !Descricao.getText().isEmpty()){
             AloToUpdate.setAlojamentoNome(Nome.getText());
             //AloToUpdate.setAlojamentoCidade(Cidade.getText());
             AloToUpdate.setAlojamentoLatitude(Lat.getText());
             AloToUpdate.setAlojamentoLongitude(Long.getText());
             AloToUpdate.setAlojamentoCp(Cp.getText());
             AloToUpdate.setAlojamentoPais(pais.getText());
             AloToUpdate.setAlojamentoCidade(morada.getText());
             AloToUpdate.setAlojamentoDescricao(Descricao.getText());
             
            AlojamentoJpaController.update(AloToUpdate);
            JOptionPane.showMessageDialog(null, "Alojamento editado Com sucesso!");
            ListarAlojamento listarAlojamento = new ListarAlojamento();
            listarAlojamento.setVisible(true);            
            this.setVisible(false);
            }
            else{
                this.jLabel13.setText("Campos Vazios2");
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void CpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
    }//GEN-LAST:event_jButton1ActionPerformed
        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       ListarAlojamento user = new  ListarAlojamento(cliente);
       user.setVisible(true);
       setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarAlojamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cp;
    private javax.swing.JTextArea Descricao;
    private javax.swing.JTextField Lat;
    private javax.swing.JTextField Long;
    private javax.swing.JTextField Nome;
    private javax.swing.JButton add;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField morada;
    private javax.swing.JTextField pais;
    // End of variables declaration//GEN-END:variables

    
    Browser browser;
    BrowserView view;
    
    private void open_site(){
        
       
        BrowserUtil.setVersion(Version.V6_22);
        browser = new Browser();
        browser.addScriptContextListener(new ScriptContextAdapter() {
            @Override
            public void onScriptContextCreated(ScriptContextEvent event) {
                browser.executeJavaScriptAndReturnValue("window").asObject().setProperty("java", new JavaCallback());
            }
        });
        BrowserView view = new BrowserView(browser);

        jPanel1.add(view, BorderLayout.CENTER);
        jPanel1.setSize(900, 500);      
        jPanel1.setVisible(true);

        // Provide the correct full path to the map.html file, e.g. D:\\map.html
        Browser.invokeAndWaitFinishLoadingMainFrame(browser, new Callback<Browser>() {
            @Override
            public void invoke(Browser value) {
                browser.loadURL("C:\\Users\\rafae\\Documents\\NetBeansProjects\\projeto2_v2.1-pontos\\simple_map.html");
            }
        });
        browser.executeJavaScriptAndReturnValue(
           

"    function geocodeLatLng(geocoder, map, infowindow, position) {\n" +
"        const latlng = {\n" +
"          lat: parseFloat(position.lat),\n" +
"          lng: parseFloat(position.lng),\n" +
"        };\n" +
"        geocoder.geocode({ location: latlng }, (results, status) => {\n" +
"          if (status === \"OK\") {\n" +
"            if (results[0]) {\n" +
"              map.setZoom(11);\n" +
"              const marker = new google.maps.Marker({\n" +
"                position: latlng,\n" +
"                map: map,\n" +
"              });\n" +
 "window.java.onMarkerAdded(position, results[0].formatted_address.toString());   "+
        "} "+
        "}});"
        + "}"

                       );
    }

    public class JavaCallback {
        public void onMarkerAdded(JSObject position, String address){
           System.out.println(address);
            //System.out.println(position.getProperty("lat").getNumberValue());
            double lattemp = Double.parseDouble(position.getProperty("lat").toString()); 
            double lngtemp = Double.parseDouble(position.getProperty("lng").toString()); 
          //double lat = position.getProperty("lat").asFunction().invoke(position).asNumber().getDouble();
          //double lng = position.getProperty("lng").asFunction().invoke(position).asNumber().getDouble(); 
           String latitude = Double.toString(lattemp);
           Lat.setText(latitude);
           String longitude = Double.toString(lngtemp);
           Long.setText(longitude);
      
       
        String[] splitted = address.split(",");
        for (int i=0; i<splitted.length; i++){
            morada.setText(splitted[0]);
            Cp.setText(splitted[1]);
            pais.setText(splitted[2]);
        }

           
        }
        
  
    }
    
  


}
